### ISSUE TITLE
Crawler can't retrieve images from Wordpress sites

### ISSUE THREAD

**Issue by Sondinhthanh** [bohdanbobrowski/blog2epub#10]
I am not a coder, so I am trying my best to describe the issue.
I attempted to convert these two sites, legatus505.blogspot.com and maxwellarchive.blogspot.com. The GUI displayed the first entry and did not continue. Terminal displayed this:

` Exception in thread Thread-1 (_download_ebook):`
` Traceback (most recent call last):`
`   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner`
`     self.run()`
`   File "/usr/lib/python3.10/threading.py", line 953, in run`
`     self._target(*self._args, **self._kwargs)`
`   File "/home/sondinhthanh/blog2epub/blog2epub/Blog2EpubKivy.py", line 191, in _download_ebook`
`     blog2epub.download()`
`   File "/home/sondinhthanh/blog2epub/blog2epub/Blog2Epub.py", line 28, in download`
`     self.crawler.save()`
`   File "/home/sondinhthanh/blog2epub/blog2epub/crawlers/Crawler.py", line 293, in save`
`     self._crawl()`
`   File "/home/sondinhthanh/blog2epub/blog2epub/crawlers/Crawler.py", line 285, in _crawl`
`     self._atom_feed_loop()`
`   File "/home/sondinhthanh/blog2epub/blog2epub/crawlers/Crawler.py", line 239, in _atom_feed_loop`
`     art.get_images()`
`   File "/home/sondinhthanh/blog2epub/blog2epub/crawlers/Crawler.py", line 600, in get_images`
`     self.process_images(self._find_images(), self._default_ripper)`
`   File "/home/sondinhthanh/blog2epub/blog2epub/crawlers/Crawler.py", line 592, in process_images`
`     img_hash = self.downloader.download_image(img)`
` UnboundLocalError: local variable 'img' referenced before assignment`

**Comment by bohdanbobrowski** [comment]
@Sondinhthanh sorry for loong response here! This issue does not occur on current version (v1.2.2) and blog is downloaded correctly, screenshots:

1. GUI:
<img width="562" alt="Zrzut ekranu 2023-10-19 o 18 50 08" src="https://github.com/bohdanbobrowski/blog2epub/assets/6423992/1abca590-57d4-4554-929a-df47170ffc8a">

2. Ebook's cover:
![maxwellarchive blogspot com_2020 09 09-2020 09 09 epub](https://github.com/bohdanbobrowski/blog2epub/assets/6423992/ab34ddef-0ef0-4f6c-a87e-b65e376710d3)
