### ISSUE TITLE
No OSX DMG, build fails, previous version damaged

### ISSUE THREAD

**Issue by whitespring** [bohdanbobrowski/blog2epub#11]
I seem to not be able to build the dmg, 

python3 setup.py 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

and the previous available DMG seems "damaged" and can not be opened.

Help please?
Thank you!

**Comment by bohdanbobrowski** [comment]
Thanks @whitespring for pointing this out. What you write is actually true... I will try to prepare a fix to that this week. It's been a while since I updated the project, and a lot has changed! Stay tuned.

**Comment by bohdanbobrowski** [comment]
@whitespring I've pushed some changes to the project, and added also new release with dmg build included: https://github.com/bohdanbobrowski/blog2epub/releases/tag/v1.2.2
