### ISSUE TITLE
Blogger issue

### ISSUE THREAD

**Issue by Zenminus** [bohdanbobrowski/blog2epub#14]
![%`KMR$A_EH3DXL{BHVI9X9X](https://github.com/bohdanbobrowski/blog2epub/assets/164884181/0a1b1415-30df-42e2-808c-f3872d48bbbd)

I am using the win 10 GUI exe.
It stopped at 5

**Comment by bohdanbobrowski** [comment]
Hi, thanks for reporting @Zenminus!
I see that you have covered the blog address in the screenshot - unfortunately, without this knowledge it will be difficult for me to fix it.
This may be due to some specific settings of the blog itself, which my program does not support.

**Comment by Zenminus** [comment]
> Hi, thanks for reporting @Zenminus! I see that you have covered the blog address in the screenshot - unfortunately, without this knowledge it will be difficult for me to fix it. This may be due to some specific settings of the blog itself, which my program does not support.

Hello Author of this application
Thank you for your work and replying!
The blogger website is 
https://latexlifestyle.blogspot.com/

**Comment by bohdanbobrowski** [comment]
This is the weirdest thing I've ever seen, but whatever...
Bug has already been patched (I also fixed a couple others). Patch will appear in the next release **v1.2.6** (I think this week), for now it can be run from sources (see branch and pull request mentioned above).

**Comment by bohdanbobrowski** [comment]
Hey @Zenminus you can try with latest release, should work far better: https://github.com/bohdanbobrowski/blog2epub/releases/tag/v1.2.6

I'm closing this issue. Further fixes will be delivered with 1.3.0
