### ISSUE TITLE
Three errors from ./blog2epubcli.py

### ISSUE THREAD

**Issue by meedstrom** [bohdanbobrowski/blog2epub#17]
Command `./blog2epubcli.py https://eukaryotewritesblog.com` failed on or after post 37: [Nemesis club](https://eukaryotewritesblog.com/2018/08/05/nemesis-club/) (next post would be [Biodiversity for heretics](https://eukaryotewritesblog.com/2018/05/27/biodiversity-for-heretics/))

    File "/src/blog2epub/crawlers/wordpress.py", line 121, in get_images_with_captions
      img_caption = img_tr.xpath('//p[@class="wp-caption-text"]/text()').pop()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    IndexError: pop from empty list

Command `./blog2epubcli.py https://agentyduck.blogspot.com/` failed on or after post 91: [Mental Postures](https://agentyduck.blogspot.com/2014/10/mental-postures.html) (next post would probably be [Simulating Confusion](https://agentyduck.blogspot.com/2014/10/simulating-confusion.html))

    File "src/lxml/apihelpers.pxi", line 1736, in lxml.etree._htmlTagValidOrRaise
    ValueError: Invalid HTML tag name 'li"'

Command `./blog2epubcli.py https://kajsotala.fi/` failed at the start.  Just a HTTP error so it may be on my end, but I wonder if you get the same too.

    File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by bohdanbobrowski** [comment]
This actually shows three separate bugs. Expect to see fix for them in version 1.3.0 wich I will try to deliver by the end of the next week.

Thanks @meedstrom for creating this issue. It's always very exciting for me, when someone uses your software :-)

**Comment by meedstrom** [comment]
Ya, a tool like this fills a distinct niche. I'm reduced to using the EpubPress extension and manually clicking each article to download, and on top of that it has a max size per book and you don't know exactly when you'll hit the max and if the download fails for that reason then you have to click all over again....

**Comment by bohdanbobrowski** [comment]
The release of the new version is taking bit longer than I've estimated above, but it should be available soon (maybe this weekend). I'm polishing the latest changes and fixing building errors (after changing from venv to poetry, it broke a bit, but it's okay now - at least for Windows). Progress can be tracked on branch 1.3.0. Meanwhile, you can see the newly added functionality: the ability to select added chapters (articles) from all downloaded ones. Stay tuned!

![obraz](https://github.com/user-attachments/assets/a51a0e4a-3542-44ee-a929-36bc0c0fcd36)

**Comment by bohdanbobrowski** [comment]
@meedstrom it looks like both bugs are finally fully resolved. I've been working on a deep code refactor for a while now... it's definitely not over yet... but it works much better now. It's currently available on the dev branch, it will be in the next 1.5.0 release.

```
blog2epub https://eukaryotewritesblog.com -l=10
blog2epub https://agentyduck.blogspot.com -l=10
blog2epub https://kajsotala.fi -l=10
```

All these commands (note the bit different syntax after cli interface refactor) produce shiny epubs, for example:

![obraz](https://github.com/user-attachments/assets/3b789a61-13ab-4151-84da-84b1e39f747a)
![obraz](https://github.com/user-attachments/assets/c094e1ce-c457-451f-8b11-5036aef65da7)

**Comment by meedstrom** [comment]
That’s nice to hear! Great work!

I’ll aim to try it soon. Maybe report new bugs on dev for your benefit 😉

**Comment by bohdanbobrowski** [comment]
@meedstrom new issues will be very welcome! :-)

**Comment by meedstrom** [comment]
Would it be possible to reverse the order of posts so that it's oldest-first? :-)

**Comment by meedstrom** [comment]
You seem to be right, I assumed it does newest-first because I saw https://eukaryotewritesblog.com/ has newest post as first page, but then the second page has some old post, it's not consistently ordered. 

But we can take this discussion to #33.
