### ISSUE TITLE
Blogspot --skip argument is not working

### ISSUE THREAD

**Issue by rakeshjain** [bohdanbobrowski/blog2epub#9]
Dear @bohdanbobrowski 

when I try to run the ./Blog2EpubCli.py with --skip=10 args, this does not work. however the -l=10 works well. 

Note: I faced this in Blogspot. Not sure about Wordpress.

Thanks.

**Comment by bohdanbobrowski** [comment]
Thanks @rakeshjain for letting me know about that! And sorry for answering so late - somehow I've missed that message. There was a bug obviously - and skip parameter was... ignored :-)
I've pushed a comit with a fix couple secons ago.
